### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JessicaxD** [SaltyGrandpa/salty_crafting#1]
Geting this Error when im pressing E on the circul 

Error running system event handling function for resource salty_crafting: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:7: attempt to index a nil value (global 'ESX')
stack traceback:
        server.lua:7: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by SaltyGrandpa** [comment]
This is because the resource relies on ESX being installed _and running_ before the resource starts. Add `start salty_crafting` after starting es_extended in your `server.cfg` to resolve.
