### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Inkovskyy** [SaltyGrandpa/salty_crafting#4]
I have a problem, when im trying to craft item - nothing show up. (After clicking "craft item" button in craft menu). I selected 2 iron in ingredients and im trying to craft "drill" and nothing happend + i cant close the menu.

	["drill"] = { 
		{item = "iron", quantity = 2, remove = true }, 
	},

**Comment by SaltyGrandpa** [comment]
@Inkovskyy did you resolve this issue?

**Comment by Inkovskyy** [comment]
yes, i changed a name of the script ;p
